### ISSUE TITLE
Error preventing whole integration startup

### ISSUE THREAD

**Issue by adambullmer** [natekspencer/hacs-planta#53]
starting with planta 1.2.0, I've started getting errors. The error logs look like this:

```
2026-08-17 21:49:16.642 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Planta for planta
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/homeassistant/helpers/update_coordinator.py", line 434, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/planta/coordinator.py", line 90, in _async_update_data
    device = device_registry.async_get_device_by_identifier(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/planta/__init__.py", line 50, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/local/lib/python3.14/site-packages/homeassistant/helpers/update_coordinator.py", line 324, in async_config_entry_first_refresh
    await self._async_config_entry_first_refresh()
  File "/usr/local/lib/python3.14/site-packages/homeassistant/helpers/update_coordinator.py", line 359, in _async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'DeviceRegistry' object has no attribute 'async_get_device_by_identifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/homeassistant/config_entries.py", line 796, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/planta/__init__.py", line 54, in async_setup_entry
    _LOGGER.exception()
    ~~~~~~~~~~~~~~~~~^^
TypeError: Logger.exception() missing 1 required positional argument: 'msg'
```

I did have plants that should be deleted, so I'm guessing there's a correlation with that maybe?

**Comment by adambullmer** [comment]
I think I have a small fix locally so I'll make a PR shortly

**Comment by natekspencer** [comment]
What version of HA are you running? My guess is you're on an older version than this allows and I didn't get the minimum HA version updated appropriately.

Actually `hacs.json` correctly shows the minimum HA version as 2026.8.0 (when this device registry method was introduced), so it should require that as a minimum before installing

**Comment by adambullmer** [comment]
You're right, I'd figured out that the integration was using a later syntax in #54, and rather than look if it was mentioned anywhere or annotated correctly for HACS added that backport.

I will say everything else worked on `2026.6.4` as far as I can tell, (deleted/dead plant devices removed). But also fair to not want to maintain a bunch of older versions for compatibility

**Comment by natekspencer** [comment]
Yeah, it can balloon with maintainability code quickly. While the one may have been fairly benign, I'd have to make sure any new code from there was also allowed before 2026.8. And with the number of integrations I maintain, it's just not in my plans haha.
